language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - docker pull elgalu/selenium
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

script:
  - travis_retry ./run_integration_tests.sh sauceLabs
  - travis_retry ./run_integration_tests.sh browserStack
  - travis_retry ./run_integration_tests.sh testingBot
  # Run unit tests for coverage
  - mvn clean package -Pcoverage-report

after_success:
  # Report coverage results to Codecov
  - bash <(curl -s https://codecov.io/bash)
  # Report coverage results to Codacy
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r ./target/site/jacoco/jacoco.xml
  # When a tag is set and a release is being done, the image is pushed
  - ./push_image.sh

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - master
    # Regular expression for release branches. E.g. -> 2.53.1a, 3.0.1a
    - /^([0-9]|[0-9][0-9])[.]([0-9]|[0-9][0-9])[.]([0-9]|[0-9][0-9])[a-z]$/