comment:
  layout: header, changes, diff

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        target: 85%
    ignore:
      # Ignoring the servlets since it does not make sense for now to test them
      - src/main/java/de/zalando/tip/zalenium/servlet/*
