apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zalenium
        role: grid
    spec:
      containers:
        - name: zalenium
          image: dosel/zalenium
          args:
            - start
            - '--chromeContainers'
            - '1'
            - '--firefoxContainers'
            - '1'
            - '--screenWidth'
            - '1440'
            - '--screenHeight'
            - '810'
            - '--seleniumImageName'
            - 'elgalu/selenium:latest'
            - '--maxTestSessions'
            - '4'
          env:
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: 250m
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: 500m
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: 500Mi
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: 1Gi
            - name: OVERRIDE_WAIT_TIME
              value: 5m
          resources:
            requests:
              cpu: 250m
              memory: 400Mi
          ports:
            - containerPort: 4444
              protocol: TCP
          volumeMounts:
            - name: zalenium-data
              mountPath: /home/seluser/videos
      volumes:
          - name: zalenium-data
            persistentVolumeClaim:
              claimName: zalenium-data
      serviceAccountName: zalenium
      serviceAccount: zalenium
